/* Autogenerated by hxtools bin2c */
#ifndef WYOSUPPORT_JPG_H
#define WYOSUPPORT_JPG_H 1

#ifdef __cplusplus
extern "C" {
#endif

extern const unsigned char bin2c_wyosupport_jpg[80084];

#ifdef __cplusplus
} /* extern "C" */
#endif


#endif /* WYOSUPPORT_JPG_H */
